# Site
name: "Al-Minnah Farm"
title: "Al-Minnah Farm"
description: "Solusi peternakan kambing terpercaya untuk Qurban & Aqiqah Anda"
logo: 'assets/images/logo/alminnah-farm.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
url: 'https://alminnah.farm'
lang: 'id'
author:
  name: "Al-Minnah Farm"
google_analytics: 'G-S88E6P3H59'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:categories/:title/
whatsapp_number: '6281286125451' 

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Defaults
defaults:
  - scope:
      path: "_posts/katalog"
    values:
      isAvailable: true

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
